### ISSUE TITLE
Public Suffix List is empty!

### ISSUE THREAD

**Issue by ducu** [rbaier/python-urltools#9]
Anyone experiencing this recently?

    >>> from urltools import *
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/ducu/summarizer/env/lib/python2.7/site-packages/urltools/__init__.py", line 1, in         <module>
        from .urltools import *
      File "/home/ducu/summarizer/env/lib/python2.7/site-packages/urltools/urltools.py", line 47, in     <module>
        assert len(PSL) > 0, 'Public Suffix List is empty!'
    AssertionError: Public Suffix List is empty!

The file was probably updated recently but it can be downloaded.
Thanks for any tips

**Comment by mokelly** [comment]
Today we get this same error on all machines.  The underlying cause seems to be that `urlopen('https://publicsuffix.org/list/effective_tld_names.dat')` returns an empty string (which it didn't yesterday).

A workaround for now is to save a local copy of the .dat file and point to it using ENV variable `PUBLIC_SUFFIX_LIST`.
